name: Gradle Package

#on:
#  release:
#    types: [created]

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up JDK 11
        uses: actions/setup-java@v2.2.0
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Gradle
        run: gradlew build
      - name: Publish to GitHub Packages
        run: gradlew publish
        env:
          USERNAME: ${{ secrets.USERNAME }}
          TOKEN: ${{ secrets.TOKEN }}
